POST http://localhost:5000/api/dues/create
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4Y2M3NjE0NGZjZGE1Y2IzNTQ5N2FkZSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc1ODQzODkxOCwiZXhwIjoxNzU4NDQyNTE4fQ.6oahRwsmmL3CsfhYnh7SUagqm_9JPxcmN4GnYI8vK2A
Content-Type: application/json

{
  "userId": "68cc753e4fcda5cb35497adb",
  "year": 2025,
  "month": "June",
  "status": "paid"
}